import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default:  "Tdemy",
    template: "%s  | Tdemy"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <header style={{

          backgroundColor:"lightblue",
          padding:"1rem"
       }}>
         <h1>Header part</h1> 
        </header> 

       <main>
       {children}
       </main>
   

       <footer style={{

        backgroundColor:'red',
        padding:"1rem"
       }}>
         <h1>Footer part</h1>
        </footer> 
      
      </body>
    </html>
  );
}
